/* eslint-disable */

// @ts-nocheck

// This file was automatically generated by @caffeinelabs/bindgen@0.1.0.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import type { ActorMethod } from '@icp-sdk/core/agent';
import type { IDL } from '@icp-sdk/core/candid';
import type { Principal } from '@icp-sdk/core/principal';

export interface Customer {
  'id' : bigint,
  'name' : string,
  'createdAt' : Time,
  'email' : string,
  'phone' : string,
}
export type Time = bigint;
export interface Transaction {
  'id' : bigint,
  'balance' : number,
  'date' : Time,
  'createdAt' : Time,
  'description' : string,
  'credit' : number,
  'customerId' : bigint,
  'debit' : number,
}
export interface _SERVICE {
  'createCustomer' : ActorMethod<[string, string, string], Customer>,
  'createTransaction' : ActorMethod<
    [bigint, Time, string, number, number, number],
    Transaction
  >,
  'deleteCustomer' : ActorMethod<[bigint], undefined>,
  'getAllCustomers' : ActorMethod<[], Array<Customer>>,
  'getCustomer' : ActorMethod<[bigint], [] | [Customer]>,
  'getTransaction' : ActorMethod<[bigint], [] | [Transaction]>,
  'getTransactionsByCustomer' : ActorMethod<[bigint], Array<Transaction>>,
  'updateCustomer' : ActorMethod<[bigint, string, string, string], Customer>,
}
export declare const idlService: IDL.ServiceClass;
export declare const idlInitArgs: IDL.Type[];
export declare const idlFactory: IDL.InterfaceFactory;
export declare const init: (args: { IDL: typeof IDL }) => IDL.Type[];