/* eslint-disable */

// @ts-nocheck

// This file was automatically generated by @caffeinelabs/bindgen@0.1.0.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { IDL } from '@icp-sdk/core/candid';

export const Time = IDL.Int;
export const Customer = IDL.Record({
  'id' : IDL.Nat,
  'name' : IDL.Text,
  'createdAt' : Time,
  'email' : IDL.Text,
  'phone' : IDL.Text,
});
export const Transaction = IDL.Record({
  'id' : IDL.Nat,
  'balance' : IDL.Float64,
  'date' : Time,
  'createdAt' : Time,
  'description' : IDL.Text,
  'credit' : IDL.Float64,
  'customerId' : IDL.Nat,
  'debit' : IDL.Float64,
});

export const idlService = IDL.Service({
  'createCustomer' : IDL.Func([IDL.Text, IDL.Text, IDL.Text], [Customer], []),
  'createTransaction' : IDL.Func(
      [IDL.Nat, Time, IDL.Text, IDL.Float64, IDL.Float64, IDL.Float64],
      [Transaction],
      [],
    ),
  'deleteCustomer' : IDL.Func([IDL.Nat], [], []),
  'getAllCustomers' : IDL.Func([], [IDL.Vec(Customer)], ['query']),
  'getCustomer' : IDL.Func([IDL.Nat], [IDL.Opt(Customer)], ['query']),
  'getTransaction' : IDL.Func([IDL.Nat], [IDL.Opt(Transaction)], ['query']),
  'getTransactionsByCustomer' : IDL.Func(
      [IDL.Nat],
      [IDL.Vec(Transaction)],
      ['query'],
    ),
  'updateCustomer' : IDL.Func(
      [IDL.Nat, IDL.Text, IDL.Text, IDL.Text],
      [Customer],
      [],
    ),
});

export const idlInitArgs = [];

export const idlFactory = ({ IDL }) => {
  const Time = IDL.Int;
  const Customer = IDL.Record({
    'id' : IDL.Nat,
    'name' : IDL.Text,
    'createdAt' : Time,
    'email' : IDL.Text,
    'phone' : IDL.Text,
  });
  const Transaction = IDL.Record({
    'id' : IDL.Nat,
    'balance' : IDL.Float64,
    'date' : Time,
    'createdAt' : Time,
    'description' : IDL.Text,
    'credit' : IDL.Float64,
    'customerId' : IDL.Nat,
    'debit' : IDL.Float64,
  });
  
  return IDL.Service({
    'createCustomer' : IDL.Func([IDL.Text, IDL.Text, IDL.Text], [Customer], []),
    'createTransaction' : IDL.Func(
        [IDL.Nat, Time, IDL.Text, IDL.Float64, IDL.Float64, IDL.Float64],
        [Transaction],
        [],
      ),
    'deleteCustomer' : IDL.Func([IDL.Nat], [], []),
    'getAllCustomers' : IDL.Func([], [IDL.Vec(Customer)], ['query']),
    'getCustomer' : IDL.Func([IDL.Nat], [IDL.Opt(Customer)], ['query']),
    'getTransaction' : IDL.Func([IDL.Nat], [IDL.Opt(Transaction)], ['query']),
    'getTransactionsByCustomer' : IDL.Func(
        [IDL.Nat],
        [IDL.Vec(Transaction)],
        ['query'],
      ),
    'updateCustomer' : IDL.Func(
        [IDL.Nat, IDL.Text, IDL.Text, IDL.Text],
        [Customer],
        [],
      ),
  });
};

export const init = ({ IDL }) => { return []; };